In [216]:
import numpy as np
from sklearn.cluster import DBSCAN
import re
import nibabel as nib

In [217]:
pathFile = open("pathFile1.txt","r")
paths = len(open("pathFile1.txt","r").readlines())
longestPathLength = int((len(max(open("pathFile1.txt","r"),key=len).split(" "))-1)/3)
print(paths)
print(longestPathLength)
usingIntensity = 1
dilationRadius = 3 #has to be greater that 1
numIntensityParams = (usingIntensity*(2*dilationRadius-1)**2) #number of intensities to use
print(numIntensityParams)

1575
59
25


In [218]:
swiImage = nib.load("SWI_Images_resize10.nii")
swiImage.shape
swiData = swiImage.get_fdata()
print(swiData.shape)
swiData = swiData/np.max(np.abs(swiData),axis=0)

(80, 105, 15)


In [219]:
# start with just the xyz and intensity of the paths nothing around it yet
bunchedPaths = {}#dictionary with the keys as the root node as a joined spring and the values as a list of all paths with that root node
flatennedPaths = {}#used for initial clustering without intesities 
groupPath = [] #dyanmic array 
for lineNum, line in enumerate(pathFile):
    currentSplitLine = line.split(" ")
    currentSplitLine = currentSplitLine[:-1]
    
    currentSplitLine = list(map(float,currentSplitLine))
    gFoldedLine = np.reshape(currentSplitLine,(int(len(currentSplitLine)/3),3))
    
    
    rootNode = " ".join(list(map(str,map(int,gFoldedLine[58]))))
    gFoldedLine.astype(np.float)
    groupArray = []
    flatGroupArray = []
    if rootNode in bunchedPaths: # if the root hasnt been added to the dictionary add it to the dictionary with a list of paths
        groupArray = bunchedPaths[rootNode] #join the string to hash a string instead of a tuple since python likes that better
        flatGroupArray = flatennedPaths[rootNode]
    else:
        bunchedPaths[rootNode] = groupArray
        flatennedPaths[rootNode] =flatGroupArray 
    flatGroupArray.append(currentSplitLine)
    
    
    gFoldedLine =gFoldedLine/np.max(gFoldedLine,axis=0)
    paddedFoldedLine = np.pad(gFoldedLine,[(0,0),(0,numIntensityParams)], "constant", constant_values = 0)
    if usingIntensity:
        for pixelNum, pixel in enumerate(gFoldedLine):
            for i in range(numIntensityParams):
                x = int(pixel[0])
                y = int(pixel[1])-dilationRadius+int((i%(2*dilationRadius-1)))
                z = int(pixel[2])-dilationRadius+int(i/(2*dilationRadius-1))
                
                if x<0 or y<0 or z<0 or x>=swiData.shape[0] or y >= swiData.shape[1] or z >= swiData.shape[2]:
                    pixelIntensity = 0 #essentially pad with 0s if the shell goes out of bounds
                else:
                    pixelIntensity = swiData[x][y][z]
                paddedFoldedLine[pixelNum][3+i] = pixelIntensity
                #print(" ".join((str(x),str(y),str(z),str(pixelIntensity))))
        #print("\n")
    
    paddedFoldedLine.astype(np.float)
    npFlattened = np.array(currentSplitLine).astype(np.float)
    groupArray.append(paddedFoldedLine)

In [220]:
print(bunchedPaths)

{'21 5 3': [array([[1.        , 0.        , 0.        , ..., 0.        , 0.63057325,
        0.56886228],
       [0.98734177, 0.        , 0.16666667, ..., 0.        , 0.61146497,
        0.60479042],
       [0.97468354, 0.        , 0.33333333, ..., 0.        , 0.61146497,
        0.60479042],
       ...,
       [0.29113924, 0.71428571, 0.33333333, ..., 0.        , 0.61146497,
        0.60479042],
       [0.27848101, 0.57142857, 0.33333333, ..., 0.        , 0.61146497,
        0.60479042],
       [0.26582278, 0.71428571, 0.5       , ..., 0.        , 0.61146497,
        0.60479042]]), array([[1.        , 0.14285714, 0.        , ..., 0.        , 0.63057325,
        0.56886228],
       [0.98734177, 0.        , 0.16666667, ..., 0.        , 0.61146497,
        0.60479042],
       [0.97468354, 0.        , 0.33333333, ..., 0.        , 0.61146497,
        0.60479042],
       ...,
       [0.29113924, 0.71428571, 0.33333333, ..., 0.        , 0.61146497,
        0.60479042],
       [0.27848101, 0.

In [221]:
print(flatennedPaths.keys())

dict_keys(['21 5 3', '21 11 12', '21 21 1', '21 27 4', '21 40 9', '21 44 7', '21 48 3', '21 55 8', '21 76 7', '21 59 11', '21 78 10', '21 85 7', '21 98 8', '21 104 5', '21 51 12', '21 13 4', '21 29 4', '21 65 9', '21 91 13', '21 91 11', '21 20 8'])


In [222]:
#just to make sure
for keys in bunchedPaths:
    bunchedPaths[keys] = np.array(bunchedPaths[keys])#.astype(np.float)
    print(bunchedPaths[keys])
    

[[[1.         0.         0.         ... 0.         0.63057325 0.56886228]
  [0.98734177 0.         0.16666667 ... 0.         0.61146497 0.60479042]
  [0.97468354 0.         0.33333333 ... 0.         0.61146497 0.60479042]
  ...
  [0.29113924 0.71428571 0.33333333 ... 0.         0.61146497 0.60479042]
  [0.27848101 0.57142857 0.33333333 ... 0.         0.61146497 0.60479042]
  [0.26582278 0.71428571 0.5        ... 0.         0.61146497 0.60479042]]

 [[1.         0.14285714 0.         ... 0.         0.63057325 0.56886228]
  [0.98734177 0.         0.16666667 ... 0.         0.61146497 0.60479042]
  [0.97468354 0.         0.33333333 ... 0.         0.61146497 0.60479042]
  ...
  [0.29113924 0.71428571 0.33333333 ... 0.         0.61146497 0.60479042]
  [0.27848101 0.57142857 0.33333333 ... 0.         0.61146497 0.60479042]
  [0.26582278 0.71428571 0.5        ... 0.         0.61146497 0.60479042]]

 [[1.         0.28571429 0.         ... 0.         0.63057325 0.56886228]
  [0.98734177 0.142857

In [223]:
for keys in flatennedPaths:
    flatennedPaths[keys] = np.array(flatennedPaths[keys])#.astype(np.float)
    print(flatennedPaths[keys])

[[79.  0.  0. ... 21.  5.  3.]
 [79.  1.  0. ... 21.  5.  3.]
 [79.  2.  0. ... 21.  5.  3.]
 ...
 [79.  0. 12. ... 21.  5.  3.]
 [79.  1. 12. ... 21.  5.  3.]
 [79.  4. 12. ... 21.  5.  3.]]
[[79.  3.  0. ... 21. 11. 12.]
 [79.  7.  8. ... 21. 11. 12.]
 [79.  8.  8. ... 21. 11. 12.]
 ...
 [79. 14. 14. ... 21. 11. 12.]
 [79. 15. 14. ... 21. 11. 12.]
 [79. 16. 14. ... 21. 11. 12.]]
[[79. 11.  0. ... 21. 21.  1.]
 [79. 12.  0. ... 21. 21.  1.]
 [79. 13.  0. ... 21. 21.  1.]
 ...
 [79. 22. 14. ... 21. 21.  1.]
 [79. 23. 14. ... 21. 21.  1.]
 [79. 24. 14. ... 21. 21.  1.]]
[[79. 26.  0. ... 21. 27.  4.]
 [79. 27.  0. ... 21. 27.  4.]
 [79. 28.  0. ... 21. 27.  4.]
 ...
 [79. 33. 14. ... 21. 27.  4.]
 [79. 34. 14. ... 21. 27.  4.]
 [79. 35. 14. ... 21. 27.  4.]]
[[79. 36.  0. ... 21. 40.  9.]
 [79. 37.  0. ... 21. 40.  9.]
 [79. 38.  0. ... 21. 40.  9.]
 ...
 [79. 44. 14. ... 21. 40.  9.]
 [79. 45. 14. ... 21. 40.  9.]
 [79. 46. 14. ... 21. 40.  9.]]
[[79. 47.  0. ... 21. 44.  7.]
 [79. 48.

In [224]:
clusteringMethod = DBSCAN(eps = 3, min_samples = 2) #DBSCAN(eps=0.5, min_samples=5, metric=’euclidean’, metric_params=None, algorithm=’auto’, leaf_size=30, p=None, n_jobs=None)[source]¶
labels = {}
for keys in flatennedPaths:
    clusteringMethod.fit(flatennedPaths[keys])
    labels[keys] = clusteringMethod.labels_
    #print(flatennedPaths[keys].shape)

In [225]:
print(labels)

{'21 5 3': array([ 0,  0,  0,  1,  1,  1,  2,  2,  2,  2,  0,  0,  3,  3,  1,  1,  1,
        2,  2,  2,  2,  0,  0,  3,  3,  3, -1,  2,  2,  2,  2,  2,  0,  0,
        3,  3,  3,  3,  2,  2,  2,  2,  4,  4,  4,  4,  4,  0,  0,  3,  3,
        3,  3,  3,  5,  5,  4,  4,  4,  4,  4,  4,  0,  0,  3,  3,  3,  3,
        5,  5,  5,  4,  4,  4,  4,  4,  4,  0,  0,  0,  3,  3,  3,  5,  5,
        5,  4,  4,  4,  4,  4,  6,  6,  6,  3,  7,  7,  5,  5,  5,  4,  4,
        4,  4,  4,  6,  6,  8,  7,  7,  7,  7,  8,  8,  8,  8,  8,  7,  8,
        8,  8,  8,  8,  9,  8,  8,  8,  8,  8,  8,  8,  9], dtype=int64), '21 11 12': array([-1,  0,  0,  0,  0,  0,  1,  1,  1,  0,  0,  0,  1,  1,  1,  0,  0,
        0,  0,  2,  1,  1,  1,  0,  0,  0,  3,  3,  4,  4,  5,  5,  2,  2,
        2,  2,  2,  0,  3,  3,  3,  3,  3,  6,  6,  5,  5,  5,  2,  2,  2,
        2,  2,  3,  3,  3,  3,  3,  3,  3,  6,  6,  6,  7,  7,  2,  2,  2,
        2,  2,  3,  3,  3,  3,  3,  3,  3], dtype=int64), '21 21 1': array([ 0

In [226]:
clusteringMethod = DBSCAN(eps = 3, min_samples = 2) #DBSCAN(eps=0.5, min_samples=5, metric=’euclidean’, metric_params=None, algorithm=’auto’, leaf_size=30, p=None, n_jobs=None)[source]¶
intensityLabels = {}
for keys in bunchedPaths:
    currentBunch = bunchedPaths[keys]
    currentBunch = np.reshape(currentBunch, (currentBunch.shape[0], currentBunch.shape[1]*currentBunch.shape[2])) #flatten
    bunchedPaths[keys] = currentBunch
    #print(currentBunch.shape)
    clusteringMethod.fit(currentBunch)
    intensityLabels[keys] = clusteringMethod.labels_

In [227]:
print(intensityLabels)

{'21 5 3': array([0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64), '21 11 12': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 0, 2, 2, 2, 2, 2, 3,
       3, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 1, 1, 1,
       1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2], dtype=int64), '21 21 1': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 2, 2, 0,
       0, 0, 0, 1, 2, 2, 2, 2, 2, 3, 3, 3, 4, 0, 1, 1, 2, 2, 2, 2, 2, 3,
       4, 4, 4

In [228]:
pathFiles = {}
for currentKey in intensityLabels:#currently uses the intensityLabels instead of the standard labels from clustering
    for index, cluster in enumerate(intensityLabels[currentKey]):
        filename = "".join(("pathClusters/",currentKey,";",str(cluster),".txt"))#format the filename based on the root node
        if filename in pathFiles:
            workingFile = pathFiles[filename]
        else:
            workingFile =  open(filename, "w+")
            pathFiles[filename] = workingFile
        #print(str(flatennedPaths[currentKey][cluster]))
        line = str(flatennedPaths[currentKey][index])[1:-1] #flattened paths contain the unedited paths hashed by the root node
        line = re.sub("'|\n|[|]", "", line) #get rid of junk characters when converting from an array to a string
        workingFile.write(" ".join((line,"\n")))
        

In [229]:
allPathFiles = open("pathClusters/allPathFiles.txt","w+")
for fileKeys in pathFiles:
    allPathFiles.write(pathFiles[fileKeys].name)
    allPathFiles.write("\n")
    pathFiles[fileKeys].close()
allPathFiles.write(str(clusteringMethod))
allPathFiles.close()

In [230]:
bunchFile = open("bunchedPaths.txt","w+")
for keys in bunchedPaths:
    for line in bunchedPaths[keys]:
        for pixelSet in line:
            bunchFile.write(re.sub("'|\n|[|]", "", str(pixelSet)))
            bunchFile.write("\n")
        bunchFile.write("\n")
bunchFile.close

<function TextIOWrapper.close()>

In [231]:
a = [1,2,3,4,5,6,7,8,9,10]
a =np.reshape(a,(5,2))
print(a)
#a = np.pad(a,[(0,0),(0,5)], "constant", constant_values = 0 )
#print(a)
a = a/np.max(a,axis=0)
print(a)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[0.11111111 0.2       ]
 [0.33333333 0.4       ]
 [0.55555556 0.6       ]
 [0.77777778 0.8       ]
 [1.         1.        ]]


In [232]:
print(swiData[68][8][1])

0.8013698630136986


In [233]:
for i in range(numIntensityParams):
    y = int((i%(2*dilationRadius-1)))
    z = int(i/(2*dilationRadius-1))
    print(y,z, sep = " ")
print(numIntensityParams)

0 0
1 0
2 0
3 0
4 0
0 1
1 1
2 1
3 1
4 1
0 2
1 2
2 2
3 2
4 2
0 3
1 3
2 3
3 3
4 3
0 4
1 4
2 4
3 4
4 4
25
